# Generated by Django 4.2 on 2023-08-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_language_remove_book_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page_count',
        ),
    ]
