# Generated by Django 4.2 on 2023-09-14 13:12

from django.db import migrations, models
import ebooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0006_book_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook_path',
            field=models.FileField(blank=True, null=True, upload_to=ebooks.models.get_file_path),
        ),
    ]
