# Generated by Django 4.2 on 2023-09-20 08:16

from django.db import migrations, models
import ebooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0008_userbookprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=ebooks.models.get_cover_image_path),
        ),
    ]
